export const data = [
  {
    src: "/data/close.webp",
    alt: "close up of trinket",
    width: 348,
    height: 232,
  },
  {
    src: "/data/drift.webp",
    alt: "drifting car",
    width: 348,
    height: 232,
  },
  {
    src: "/data/man.webp",
    alt: "man on railing",
    width: 320,
    height: 480,
  },
  {
    src: "/data/mono.webp",
    alt: "two cars in monochrome",
    width: 348,
    height: 232,
  },
  {
    src: "/data/mustang.webp",
    alt: "blue mustang",
    width: 348,
    height: 232,
  },
  {
    src: "/data/racecars.webp",
    alt: "racecars",
    width: 348,
    height: 232,
  },
  {
    src: "/data/trailer.webp",
    alt: "car on trailer",
    width: 348,
    height: 232,
  },
  {
    src: "/data/tesla.webp",
    alt: "red tesla",
    width: 320,
    height: 480,
  },
  {
    src: "/data/wheel.webp",
    alt: "close up of steering wheel",
    width: 348,
    height: 232,
  },
  {
    src: "/data/woman.webp",
    alt: "woman in field",
    width: 348,
    height: 232,
  },
  {
    src: "/data/close.webp",
    alt: "close up of trinket",
    width: 348,
    height: 232,
  },
  {
    src: "/data/drift.webp",
    alt: "drifting car",
    width: 348,
    height: 232,
  },
  {
    src: "/data/man.webp",
    alt: "man on railing",
    width: 287,
    height: 480,
  },
  {
    src: "/data/mono.webp",
    alt: "two cars in monochrome",
    width: 348,
    height: 232,
  },
  {
    src: "/data/mustang.webp",
    alt: "blue mustang",
    width: 348,
    height: 232,
  },
  {
    src: "/data/racecars.webp",
    alt: "racecars",
    width: 348,
    height: 232,
  },
  {
    src: "/data/trailer.webp",
    alt: "car on trailer",
    width: 348,
    height: 232,
  },
  {
    src: "/data/tesla.webp",
    alt: "red tesla",
    width: 287,
    height: 480,
  },
  {
    src: "/data/wheel.webp",
    alt: "close up of steering wheel",
    width: 348,
    height: 232,
  },
  {
    src: "/data/woman.webp",
    alt: "woman in field",
    width: 348,
    height: 232,
  },
];
